version: '3.4'

services:
  daprcounter:
    image: ${DOCKER_REGISTRY-}daprcounter
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

  daprcounter-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
    "-app-id", 
    "daprcounter",
    "-components-path", "/components",
    "-config", "/configuration/config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - daprcounter
    network_mode: "host"
