apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorserver-deploymnet
  labels:
    app: bsa
  #namespace: dapr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsa
  template:
    metadata:
      labels:
        app: bsa
    spec:
      containers:
        - name: bsa
          image: blazorserverapp:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: blazorserver-service
  #namespace: dapr-system
spec:
  type: LoadBalancer
  selector:
    app: bsa
  ports:
    - port: 8080
      targetPort: 80