apiVersion: v1
kind: Service
metadata:
  name: blazorserver-app
  namespace: dapr-system
spec:
  type: LoadBalancer
  selector:
    app: bsa
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorserver-app
  labels:
    app: bsa
  namespace: dapr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsa
  template:
    metadata:
      labels:
        app: bsa
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "blazorserver-app"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: bsa
          image: blazorserverapp:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
              protocol: TCP