apiVersion: apps/v1
kind: Service
metadata:
  name: daprbackend-api
  namespace: dapr-system
  labels:
    app: dbe
    service: daprbackend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
      protocol: TCP
      name: http
  selector:
    service: daprbackend

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: daprbackend
  namespace: dapr-system
  labels:
    app: dbe
    service: daprbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: daprbackend
  template:
    metadata:
      labels:
        app: dbe
        service: daprbackend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprbackend-api"
        dapr.io/app-port: "80"
      #  dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: daprbackend-api
          image: daprbackend:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
              protocol: TCP